file:
  img_dir:      "_DIFFSHOTS"
  markdown:     "_DIFFSHOTS.md"

font:
  family:       "Consolas"
  size:         "16"
  height:       "20"
  
color:
  hide:         "#aaaaaa"
  delete:       "#ff0000"
  add:          "#00ff00"
  normal:       "#ffffff"
  background:   "#000000"
  
image:
  width:        "800"
  quality:      "0"
  